#!/usr/bin/env python3
import sys
import subprocess
import os
import time
import argparse
import re

def run_cmd(args, check=True, capture=True):
    """Helper to run a shell command."""
    try:
        res = subprocess.run(
            args, 
            capture_output=capture, 
            text=True, 
            check=check
        )
        return res
    except subprocess.CalledProcessError as e:
        print(f"Command {' '.join(args)} failed with exit code {e.returncode}")
        if capture:
            print(f"Stdout: {e.stdout}")
            print(f"Stderr: {e.stderr}")
        raise e

def main():
    parser = argparse.ArgumentParser(description="Automates running tests and creating a GitHub Pull Request to development.")
    parser.add_argument("--branch", help="Name of the branch to create/checkout.")
    parser.add_argument("--commit-msg", help="Commit message for uncommitted changes.")
    parser.add_argument("--title", help="Title of the pull request.")
    parser.add_argument("--body", help="Body/description of the pull request.")
    args = parser.parse_args()

    # 1. Run tests
    print("Step 1: Running pytest...")
    try:
        # Use python3 -m pytest to run the test suite
        run_cmd([sys.executable, "-m", "pytest"], check=True, capture=False)
        print("✓ All tests passed successfully.")
    except Exception:
        print("❌ Test suite failed. Please fix tests before creating a pull request.")
        sys.exit(1)

    # 2. Check git status & setup branch names
    print("\nStep 2: Checking git status...")
    status_res = run_cmd(["git", "status", "--porcelain"])
    has_changes = len(status_res.stdout.strip()) > 0

    # Ensure remote origin is defined
    remotes = run_cmd(["git", "remote"])
    if "origin" not in remotes.stdout:
        print("❌ Error: Remote 'origin' is not configured in this git repository.")
        sys.exit(1)

    # Establish target branch name
    timestamp = int(time.time())
    branch_name = args.branch if args.branch else f"feature/auto-pr-{timestamp}"
    commit_msg = args.commit_msg if args.commit_msg else f"Auto-commit: update code ({timestamp})"
    pr_title = args.title if args.title else f"Feature update ({timestamp})"
    pr_body = args.body if args.body else "This pull request was automatically generated by the /pr-create command."

    # Determine current branch
    branch_res = run_cmd(["git", "branch", "--show-current"])
    original_branch = branch_res.stdout.strip()
    print(f"Current branch: {original_branch}")

    # Check if target branch development exists on remote origin. If not, create it from origin/main
    print("\nStep 3: Checking remote 'development' branch...")
    ls_remote = run_cmd(["git", "ls-remote", "--heads", "origin", "development"])
    if "development" not in ls_remote.stdout:
        print("Remote 'development' branch does not exist. Creating it from origin/main...")
        try:
            # Push local main/current branch to create remote development branch if origin/main doesn't exist
            # Check what default branch is on origin
            default_branch_res = run_cmd(["git", "symbolic-ref", "refs/remotes/origin/HEAD"], check=False)
            default_branch = "main"
            if default_branch_res.returncode == 0:
                default_branch = default_branch_res.stdout.strip().split('/')[-1]
            
            run_cmd(["git", "push", "origin", f"origin/{default_branch}:refs/heads/development"])
            print("✓ Remote 'development' branch created successfully.")
        except Exception as e:
            print(f"⚠️ Warning: Could not create remote 'development' branch automatically: {e}")

    # Switch to/create the new branch
    print(f"\nStep 4: Switching to branch '{branch_name}'...")
    local_branches = run_cmd(["git", "branch"])
    branch_exists_locally = any(b.strip().replace("* ", "") == branch_name for b in local_branches.stdout.split('\n'))

    if branch_exists_locally:
        run_cmd(["git", "checkout", branch_name])
    else:
        run_cmd(["git", "checkout", "-b", branch_name])
    print(f"✓ Checked out branch '{branch_name}'.")

    # Commit uncommitted changes if any
    if has_changes:
        print("\nStep 5: Committing changes...")
        run_cmd(["git", "add", "-A"])
        run_cmd(["git", "commit", "-m", commit_msg])
        print(f"✓ Committed changes: '{commit_msg}'")
    else:
        print("\nStep 5: No uncommitted changes detected.")
        # Check if there are any commits between development and our new branch
        # Fetch development first to ensure it's up to date
        run_cmd(["git", "fetch", "origin", "development"], check=False)
        log_res = run_cmd(["git", "log", "origin/development..HEAD"], check=False)
        if log_res.returncode != 0 or not log_res.stdout.strip():
            print("No new commits compared to origin/development. Creating an empty commit to trigger PR...")
            run_cmd(["git", "commit", "--allow-empty", "-m", f"Trigger PR creation ({timestamp})"])
            print("✓ Created empty commit.")

    # Push to origin
    print(f"\nStep 6: Pushing branch '{branch_name}' to remote origin...")
    run_cmd(["git", "push", "-u", "origin", branch_name])
    print("✓ Branch pushed successfully.")

    # Create the pull request using GitHub CLI (gh)
    print("\nStep 7: Creating GitHub pull request to 'development'...")
    try:
        pr_res = run_cmd([
            "gh", "pr", "create",
            "--base", "development",
            "--head", branch_name,
            "--title", pr_title,
            "--body", pr_body
        ])
        
        pr_output = pr_res.stdout.strip()
        print(f"GitHub CLI Output: {pr_output}")

        # Try to parse the URL and number from the output
        # gh pr create output is usually the URL: https://github.com/owner/repo/pull/num
        match = re.search(r"https://github\.com/[^/]+/[^/]+/pull/(\d+)", pr_output)
        if match:
            pr_num = match.group(1)
            print("\n==========================================")
            print("🎉 SUCCESS: Pull Request Created!")
            print(f"PR_LINK: {pr_output}")
            print(f"PR_NUMBER: {pr_num}")
            print("==========================================")
        else:
            print("\n==========================================")
            print("🎉 SUCCESS: Pull Request Created!")
            print(f"PR_LINK: {pr_output}")
            print("==========================================")

    except Exception as e:
        print(f"❌ Failed to create Pull Request: {e}")
        # Switch back to original branch
        run_cmd(["git", "checkout", original_branch], check=False)
        sys.exit(1)

    # Return to the original branch
    run_cmd(["git", "checkout", original_branch])
    print(f"\n✓ Returned to original branch '{original_branch}'.")

if __name__ == "__main__":
    main()
